#Rutas donde se van a almacenar los ficheros del WIDS
pcap_path: '/home/chengo/tfm/pcaps/'
log_path: '/tmp/wids_logs/'
filename: '/tmp/sniff.pcap'
#Ińdice fichero a analizar
n_fichero: 1
#Límites de tramas recibidas para definir los ataques
max_dos: 10
max_ksk: 3
#Nivel de detalle de las alertas mostradas
detail_level: 1
#'' para no tener ningún AP configurado
#SSID y número de puntos de acceso con dicho SSID
ssid: ''
ssid_n: ''
